### ISSUE TITLE
000007

### ISSUE THREAD

**Issue by MFobeid** [VPRL/Virginia-Philosophy-Reality-Lab#44]
# Beta Testing #

* There are two active paths you can take to help us beta test this experience. 
* We will give you 2 unique codes to test both paths, one will be an even number and one will be an odd number.
  * If you enter in an even number you will be participating in the **switch** study.
  * If you enter in an odd number you will be participating in the **push** study. 
* Please attempt to answer the following questions to the best of your ability.

## Equipment Details ##
>Please select one:

- [ ] Oculus Quest 1
- [X] Oculus Quest 2
- [ ] Oculus Quest Rift S
- [ ] Oculus OG 🕶️

## Scenario Details ###
>Please describe the scenario as you experienced it

*The experiences started in an office. I believe this part of the scene served the purpose of acquainting the user with the type of visuals, interactions, audio cues, and controls they can expect. It also served as the launching place from which they can go to different paths based on the code they enter. Next, I was transported to a different scene where I was in a control room of an under-construction railway station. I was asked to direct an automated train to either of the two paths, curve or bridge. I was also taught that dropping any item such as a liquid or a person (God forbid) onto the track, it will cause the train to stop. I was then involved in two different incidents. The first was that there was an unexpectedly incoming train headed toward the curve where there were workers on track, so I pushed a barrel of liquid to stop it. The other one was more intense, because both paths of the track needed maintenance and a group of workers were attending to the curve portion, meanwhile, a worker was attending to the barrel dispenser very close to me, and a train was incoming headed to the curve. The dilemma I had was how do I save the workers on the track, so I tried my best to push the lever to direct the train to the bridge expecting it will cause an explosion or fire, but at least I'm aware that the train is unoccupied so no human casualties will be caused. But my efforts were in vain as the lever didn't move and the train cruelly passed through the curve and everyone on it.*

## Beta Test Version ###
>This should be [0.1.0-beta](https://github.com/vmasc-odu/Virginia-Philosophy-Reality-Lab/releases/tag/0.1.0-beta)

### Estimated Time ###
> Please provide the rough time you started the experience and use time zones, e.g. *12:30am EST May 4, 2021*
*10:20am EST June 22, 2021*

### Qualtrics Code ###

> Please enter the 6 digit survey code you used here e.g. '123456'
*000007*

### Training Decision on Pulling the Switch ###
>Please select one:

- [ ] Followed Directions: sent the train towards the bridge 🌉
- [x] You Caused Trouble: sent the train towards the curve 

### Training Decision on Stopping the Train with the Barrel ###
>Please select one:

- [x] Followed Directions: pushed the barrel to stop the train
- [ ] You Caused Trouble: did not push the barrel and the system took over

### Moral Control Decision ###
>Please select one:

*For EVEN survey code (Switch Study)*
- [ ] You sent the train away from the people
- [ ] You did nothing and the five people died 🤯
- [ ] You did nothing and the five people lived 🐛

*For ODD survey code (Push Study)*
- [ ] You stopped the train with a Barrel
- [x] You did nothing and the five people died 🤯
- [ ] You did nothing and the five people lived 🐛

### Test Study Decision ###
>Please select one:

*For EVEN survey code (Switch Study)*
- [ ] You pulled the switch, killed 1, saved 5
- [ ] You did *not* pull the switch, killed 5

*For ODD survey code (Push Study)*
- [ ] You pushed a person, killed 1, saved 5
- [x] You did *not* push a person, killed 5

### System Crash ##
- [x] Did you Encounter a Crash?
> Please explain what happened, do you remember if you were interacting with anything? Do you remember about where you were in the experience?

*When I first tried to run the experience, as I'm traveling, I had no access to internet but I did side load the APK before my travel. But when I tried to run it without access to wifi, a few seconds after loading into the office scene, it would crash before audio instructions would start.
Only after connecting to wifi did it work normally.*

> If you want to be really helpful 🥰 and you think you can recreate the crash and know how to run adb logcat please dump us the file here! 
> If not no worries, we still 🖤 you.
*I would do this if I wasn't traveling, sorry and I 🖤 you too.*

### Additional Comments & Details ###
>Any other feedback? Notes? Suggestions? Little things you noticed? Anything?! Please and thank you!😺

*Great work with error proofing, UI, and ensuring accessibility. There are several things that I look for in a successful VR experience from a design and HCI perspective and your work checks many boxes of mine. This includes asking the user about their position and adjusting the XR rig accordingly, good collider definitions for objects in the office, spring-based buttons on dashboard in office scene, close captioned audio instructions, audio and visual cues when hovering and selecting objects, automatic follow-through of the lever movement (typically an annoying interaction in VR), audio sound effects for various speakers (nice voice J!), and utility tools/settings on the hand watch are well implemented.
Things I would add as improvements:
- When inside the office looking out the window, the far clipping plane seems to intersect with the mountain, I recommend increasing that or adding a skybox.
- Add glide, vignette, or slower fade to teleportation for locomotion
- When pushing the barrel, it only works using a direct interaction (not using a raycast) where they need to teleport closer to the window. So this should be made clear to the user.
- I would tilt the control board by 30 degrees toward the user as it will be easier to read
- The "5 workers" indicator, although in red is a little subtle on a flat surface. Perhaps make it would be wise to tell the user that they can also use the board to find indicators of people on the track. And also the fact that there's a similar indicator on the camera feed.
- A skip button for the first set of instructions would be nice, for those doing this on the 2nd attempt or more.
- In some cases, the wristwatch seems to float away from the controller/hand, it gets fixed once the trigger is pressed.
- There might be a need to let the participants know whether their answers are anonymized or not before the study, as well as their audio recording.*

**Comment by JShull** [comment]
Hey @MFobeid thanks for the feedback - we didn't actively respond to your information here but it was shared within the last few weeks of our attempts to seriously overall the entire experience. 

Yes an active data connection is required right now because for the IRB portion we are pulling back a lot of data - we did add in a check that explains this so before you get to the tower the system informs you that you need wifi and kicks you out. We have no offline sync mode -  the non-data collecting one will work offline as we will have zero data hooks in it - this version should be ready before the fall.

- Clipping Planes are fixed 😸 
- Fading to teleport will be added in the more public facing support - unfortunately at the time this was built onto MRTK and they don't directly support this. There are easy ways to do this and at the moment given we only really have 2 super active zones I just didn't get to it. MRTK as a whole should probably revamp their teleporting system, that's the one area of their toolkit that is a little less expansive... our current teleporting system is actually a world/local hack of how MRTK generates user position combined with MRTK interactable items. In order to allow a self adjusting for varying heights/seats because at the time the OS didn't support this - really had to break a lot of MRTK world position stuff just to get this to work as it is... one area of MRTK that I would suggest changes.
- We no longer accept raycasting at all once your in the tower and everything is now a physics based interaction - we actually have reduced a lot of our "instructions" to hopefully reduce confusion. I do think we could update some of our initial instructions but for the time being that level of effort is going to go into the public facing tools we are going to be building - as we all agree this has more value for users and other developers/educators.
- We moved for the most part all important information to the TV monitor in the tower - much easier to read and easier to see what's going on (no more track on the board) we pulled the switch entirely and now it's just two big buttons. Actually the entire track configuration and user perspective is completly different so this removed the need of adding TVs and/or the whole 'CCTV' system. We really wanted to simplify what we had based on the combined feedback.
- We added a few accessibility features to let you adjust your seat/stand height to help with reading and/or comfort levels based on individuals heights/preferences - this makes the entire experience a lot nicer and even easier to test/go through 😸 
- We will be incorporating a skip feature (I have one already for development testing) but we don't want to introduce it yet to the IRB study - for the non data collecting version we are putting out in a month or so this will be 💯 added in.
- The floating wristwatch is really a product of Oculus/Unity/MRTK at somepoint when it's all OpenXR underneath the hood I think those things will be easier to catch (poll for drift/lack of motion and hide controller vs letting it still be rendered)
- The IRB information provided on the pre-survey has all of this in it...

If you did want a copy of your data let me know - it's on our older system (we've swapped over to another backend on the latest version) 

Really grateful for your feedback and constant support!
